// @ts-check
// Cada seção lê os arquivos da própria pasta. Para mudar a ordem,
// use `sidebar_position` no cabeçalho (front matter) de cada página.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  amostras: [{type: 'autogenerated', dirName: 'amostras'}],
  casos: [{type: 'autogenerated', dirName: 'estudos-de-caso'}],
};

export default sidebars;
